### PR TITLE
fix: remove unnecessary nesting of get order details response

### LINKED ISSUE #62: Order details response is nested under `data` field
image
As in image, response is unnecessarily nested under `data` field for get order details endpoint.

### PR DESCRIPTION
**Pull request by sourabhxyz**
Closes #62, #63. See linked issues for more details.

Also adds bot variant of multi fill endpoint.

### CODE REVIEW

File: geniusyield-server-lib/src/GeniusYield/Server/Dex/PartialOrder.hs [hunk 1]
```diff
@@ -376,8 +376,7 @@ type OrdersAPI =
       :> Description "Get details of an order using it's unique NFT token. Note that each order is identified uniquely by an associated NFT token which can then later be used to retrieve it's details across partial fills."
       :> "details"
       :> Capture "nft-token" GYAssetClass
-      :> Throws PodOrderNotFound
-      :> Get '[JSON] OrderInfoDetailed
+      :> UVerb 'GET '[JSON] '[WithStatus 200 OrderInfoDetailed, WithStatus 404 PodOrderNotFound]
```
Comment (sourabhxyz) [inline geniusyield-server-lib/src/GeniusYield/Server/Dex/PartialOrder.hs:379]: Have made a move from [`servant-checked-exceptions`](https://github.com/cdepillabout/servant-checked-exceptions#readme) to the approach mentioned [here](https://docs.servant.dev/en/stable/cookbook/uverb/UVerb.html).

**Review by ajuggler — APPROVED** [review]
Reviewed.
